config/routes.rb
Rails.application.routes.draw do

  get 'features/edit'

  get 'venues/all_events'

  get 'bookings/all'

  get 'bookings/shopping_cart'

  post 'stripe_checkout' => 'bookings#stripe_checkout'

  get 'search' => 'events#search'

  get 'acts/all_events'

  root to: 'events#index'

  resources :events do 
    resources :bookings
  end
  resources :venues
  resources :acts
  resources :genres
  resources :charges
  resources :features
  resources :admin

  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    user ||= User.new

    if user.role? :admin
      can :manage, :all
    else
      can :read, [Event, Act, Venue]
      can :manage, Booking, user_id: user.id
      #can :create, Comment
      #can :update, Comment
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/act.rb
class Act < ActiveRecord::Base

  belongs_to :event
  has_many :events
  has_many :venues, :through => :event
  has_many :bookings, :through => :event
  has_many :genres, :through => :event

  def self.search(search)
    where("act_name LIKE ?", "%#{search}%")
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  require 'time'

  belongs_to :event
  belongs_to :user
  has_many :venues, :through => :event
  has_many :acts, :through => :event
  has_many :genres, :through => :event

  scope :unpaid, -> {where(:paid => nil)}
  scope :paid, -> {where(:paid => true)}

  def self.unpaid_grouped_events
    Booking.unpaid.group("event_id")
  end

  def expired?
    (Time.now - 100) > created_at
  end
  #7200 - 2 hours

  def self.two_hour_bookings
    checkout_bookings = Booking.unpaid
    counter = 0;
    checkout_bookings.each do |booking|
      if booking.expired?
        booking.destroy
        counter += 1
      end
    end
    return counter
  end

end

app/models/controller.rb
class Controller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :act
  belongs_to :venue
  belongs_to :feature
  has_many :bookings
  has_many :users, :through => :bookings
  has_many :event_genres
  has_many :genres, :through => :event_genres

  def self.search(search)
    where("event_details LIKE ?", "%#{search}%")
  end

  def double_booking?
    self.venue.events.each do |event|
      if event == self
        next
      end
      range = (event.event_start_time.to_i .. event.event_end_time.to_i)
      if (range) === self.event_start_time.to_i
        return "Event already Booked at this Time at this Venue"
      elsif (range) === self.event_end_time.to_i
        return "Event already Booked at this Time at this Venue"
      end
    end
    return nil
  end

  def tickets_left?
    event = Event.find(self.id)
    booking_count = event.bookings.count
    tickets_left = event.venue.venue_capacity - booking_count
  end

  def sold_out?
    event = Event.find(self.id)
    booking_count = event.bookings.count
    tickets_left = event.venue.venue_capacity - booking_count
    if tickets_left > event.venue.venue_capacity
      return true
    else
      return false
    end
  end

end

app/models/event_genre.rb
class EventGenre < ActiveRecord::Base

  belongs_to :event
  belongs_to :genre

end

app/models/feature.rb
class Feature < ActiveRecord::Base

  belongs_to :event

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :event_genres
  has_many :events, :through => :event_genres

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
  has_many :events, :through => :bookings

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base

  belongs_to :event
  has_many :events
  has_many :acts, :through => :event
  has_many :bookings, :through => :event

  def self.search(search)
    by_location = where("venue_location LIKE ?", "%#{search}%")
    by_name = where("venue_name LIKE ?", "%#{search}%")
    (by_location + by_name).uniq
  end

end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/admin_helper.rb
module AdminHelper

end

app/helpers/application_helper.rb
module ApplicationHelper

  def admin?
    current_user.role == "admin"
  end
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/admin/index.html.erb
<section class="row">
  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Events<h3>
      </div>
      <%= link_to "Add New Event", new_event_path %>
      <br>
      <br>
      <% @events.each do |event| %>
        <%= event.event_details %>
        <%= link_to "Edit", edit_event_path(event.id) %>
        <br>
        <br>
      <% end %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Venues<h3>
      </div>
      <%= link_to "Add New Venue", new_venue_path %>
      <br>
      <br>
      <% @venues.each do |venue| %>
        <%= venue.venue_name %>
        <%= link_to "Edit", edit_venue_path(venue.id) %>
        <br>
        <br>
      <% end %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Bookings<h3>
      </div>
      <% @bookings.each do |booking| %>
        <%= booking.user.email %>
        <br>
        <%= booking.event.event_details %>
        <br>
        <br>
      <% end %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Users<h3>
      </div>
      <% @users.each do |user| %>
        <%= user.email %>
        <br>
        <% if user.role == "admin" %>
          <%= "Admin User" %>
        <% end %>
        <br>
        <br>
      <% end %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Acts<h3>
      </div>
      <%= link_to "Add New Act", new_act_path %>
      <br>
      <br>
      <% @acts.each do |act| %>
        <%= act.act_name %>
        <%= link_to "Edit", edit_act_path(act.id) %>
        <br>
        <br>
      <% end %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Featured Events<h3>
      </div>
      <br>
      <br>
      <% @featured.each do |feature| %>
        <%= feature.event.event_details %>
        <%= link_to "Change This Feature", edit_feature_path(feature.id) %>
        <br>
        <br>
      <% end %>
    </div>
  </div>  

</section> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketyBoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header-image">
    <h1>Tickety-Boo!</h1>
  </div>
  <nav>
    <div class="container">
      <div class="nav-left">
        <ul>
          <li class="welcome"><%= link_to "Tickety-Boo!", root_path %></li>
          <li>
            <%= form_tag(search_path, method: :get, id: "search_form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search Here" %>
              <%= submit_tag "Search" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="nav-right">
        <ul>
          <% if user_signed_in? %>
            <li class="welcome">Welcome back: <%= current_user.email %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <li class="logo"><%= link_to(content_tag(:i, nil, class: 'fa fa-ticket fa-2x'), bookings_all_path) %></li>
            <li class="logo"><%= link_to(content_tag(:i, nil, class: 'fa fa-shopping-cart fa-2x'), bookings_shopping_cart_path) %></li>
          <% else %>
            <li class="welcome"><%= link_to "Sign In", new_user_session_path %></li>
          <% end %> 
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% if user_signed_in? && admin? %>
      <%= link_to "Admin Panel", admin_index_path %>
    <% end %>
  </div>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </div>

  <footer>
    <div class="container">
      <div class="footer-left">
      <ul>
        <li class="logo" ><i class="fa fa-facebook-official"></i></li>
        <li class="logo"><i class="fa fa-twitter-square"></i></li>
        <li class="logo"><i class="fa fa-pinterest-p"></i></li>
        <li class="logo"><i class="fa fa-github"></i></li>
      </ul>
      </div>
      <div class="footer-right">
        <ul>
          <li class="logo"><i class="fa fa-copyright"></i>Tickety-Boo!</li>
        </ul>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>