config/routes.rb
Rails.application.routes.draw do

  get 'features/edit'

  get 'venues/all_events'

  get 'bookings/all'

  get 'bookings/shopping_cart'

  post 'stripe_checkout' => 'bookings#stripe_checkout'

  get 'search' => 'events#search'

  get 'acts/all_events'

  root to: 'events#index'

  resources :events do 
    resources :bookings
  end
  resources :venues
  resources :acts
  resources :genres
  resources :charges
  resources :features
  resources :admin

  devise_for :users

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  require 'time'

  belongs_to :event
  belongs_to :user
  has_many :venues, :through => :event
  has_many :acts, :through => :event
  has_many :genres, :through => :event

  scope :unpaid, -> {where(:paid => nil)}
  scope :paid, -> {where(:paid => true)}

  def self.unpaid_grouped_events
    Booking.unpaid.group("event_id")
  end

  def expired?
    (Time.now - 100) > created_at
  end
  #7200 - 2 hours

  def self.two_hour_bookings
    checkout_bookings = Booking.unpaid
    counter = 0;
    checkout_bookings.each do |booking|
      if booking.expired?
        booking.destroy
        counter += 1
      end
    end
    return counter
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  load_and_authorize_resource

  def new
    @event = Event.find(params[:event_id])
    @booking = Booking.new
    @ticket_range = (@event.tickets_left? > 6) ? 6 : @event.tickets_left?
  end

  def create
    if params[:ticket_quantity].empty?
      ticket_quantity = 1
    else
      ticket_quantity = params[:ticket_quantity][0].to_i
    end
    ticket_quantity.times do
      new_booking = Booking.new(booking_params)
      if new_booking.event.sold_out?
        redirect_to root_path, alert: "Event Sold Out"
      end
      new_booking.save
    end
  
    @user = current_user
     redirect_to(bookings_shopping_cart_path)
  end

  def shopping_cart
    @bookings = current_user.bookings.unpaid_grouped_events

    if @bookings != []
      @amounts = @bookings.map do |booking|
        (booking.event.event_price * @bookings.count[booking.event.id])

      end
      sum = @amounts.inject(:+)
      @amount = sum.to_i
      @stripe_amount = (sum*100).to_i
    end
  end

  def stripe_checkout
    bookings = current_user.bookings.unpaid_grouped_events

    amounts = bookings.map do |booking|
      (booking.event.event_price * bookings.count[booking.event.id])
    end
    sum = amounts.inject(:+)
    @stripe_amount = (sum*100).to_i

        customer = Stripe::Customer.create(
          :email => params[current_user.email],
          :source  => params[:stripeToken]
        )

        charge = Stripe::Charge.create(
          :customer    => customer.id,
          :amount      => @stripe_amount,
          :description => 'Rails Stripe customer',
          :currency    => 'gbp'
        )

    checkout_bookings = current_user.bookings.unpaid
    checkout_bookings.each do |paid_booking|
      paid_booking.update({paid: true})
    end

    redirect_to bookings_all_path
  end

  def all
    # @bookings = Booking.where({user_id: current_user.id}).paid
    @bookings = current_user.bookings.paid
  end

  def destroy
      @user = current_user.id
      booking = Booking.find(params[:id])
      booking.destroy
      redirect_to(bookings_shopping_cart_path)
    end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :event_id)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/all.html.erb
<h1><%= current_user.email %>: Your Current Bookings</h1>
<section class="row">
  <div class="grid grid-12">
    <div class="panel panel-primary">
      <% if @bookings == [] || nil %>
        <h2>No Bookings To Show!</h2>
      <% else %>
        <% @bookings.each do |booking| %>
          <%= link_to "#{booking.event.act.act_name}", act_path(booking.event.act.id) %>
          <br>
          <%= link_to "#{booking.event.event_details}", event_path(booking.event.id) %>
          <br>
          <%= booking.event.event_start_time.strftime('%H:%M on %d %^b %Y') %>
          <br>
          <%= link_to "#{booking.event.venue.venue_name}", venue_path(booking.event.venue.id) %>
          <br>
          <%= booking.event.venue.venue_location %>
          <br>
          <br>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/bookings/new.html.erb
<div class= "grid grid-6">
  <%= form_for [@event, @booking] do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :event_id, value: @event.id %>
    <br>
    <%= current_user.email %>
    <br>
    <%= @event.act.act_name %>
    <%= @event.event_details %>
    <br>
    <%= @event.venue.venue_name %>
    <br>
    <%= @event.venue.venue_location %>
    <br>
    <%= @event.event_start_time.strftime('%H:%M on %d %^b %Y') %>
    <br>
    £<%= @event.event_price %>
    <br>
    <%= label :ticket_quantity, "Select Quantity" %>
    <%= number_field :ticket_quantity, nil, :value => 1, in: 1..@ticket_range %>
    <br>
    <br>
    <%= f.submit 'Add To Basket' %>
  <% end %>
 </div> 

app/views/bookings/shopping_cart.html.erb
<h1><%= current_user.email %>: Shopping Cart</h1>
<h2><%= link_to "Continue Shopping", root_path %></h2>
<section class="row">
  <div class="grid grid-12">
    <div class="panel panel-primary">
        <% if @bookings == [] || nil %>
          <h2>Shopping Cart Empty!</h2>
        <% else %>
          <% @bookings.each do |booking| %>
          <div class="cart-left">        
            <%= booking.event.event_details %>
            <br>
            <%= booking.event.event_start_time.strftime('%H:%M on %d %^b %Y') %>
            <br>
            <%= booking.event.venue.venue_name %>
            <br>
            <p>Total Cost: <%= booking.event.event_price * @bookings.count[booking.event_id] %></p>
          </div> <!-- .cart-right -->
          <div class="cart-left">
            <p>Number of Tickets: <%= @bookings.count[booking.event_id] %></p>
            <% if @bookings.count[booking.event_id] < 6 %>
              <%= button_to("Add One Ticket", event_bookings_path(booking.event.id, :ticket_quantity => 1, booking:{:user_id => current_user.id, :event_id => booking.event.id}), method: 'post', data: {confirm: 'Add One More Ticket. Are you sure?!'} ) %>
            <% end %> 
              <br>
            <%= button_to("Remove One Ticket", event_booking_path(booking.event.id, booking.id), method: :delete, data: {confirm: 'Remove One Ticket? Are you sure?!'} ) %>
            <br>
          </div> <!-- .cart-left -->
            <br>
            <br>
          <% end %>
          <p>Total Amount: £<%= @amount %></p>
          <%= form_tag('/stripe_checkout', method: 'post') do %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                   data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                   data-currency="gbp"
                   data-amount=<%= @stripe_amount %>
                   data-email=<%= current_user.email %>
                   data-locale="auto">
           </script>
          <% end %> 
        <% end %>
    </div>
  </div>
</section>