config/routes.rb
Rails.application.routes.draw do

  get 'features/edit'

  get 'venues/all_events'

  get 'bookings/all'

  get 'bookings/shopping_cart'

  post 'stripe_checkout' => 'bookings#stripe_checkout'

  get 'search' => 'events#search'

  get 'acts/all_events'

  root to: 'events#index'

  resources :events do 
    resources :bookings
  end
  resources :venues
  resources :acts
  resources :genres
  resources :charges
  resources :features
  resources :admin

  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    user ||= User.new

    if user.role? :admin
      can :manage, :all
    else
      can :read, [Event, Act, Venue]
      can :manage, Booking, user_id: user.id
      #can :create, Comment
      #can :update, Comment
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/act.rb
class Act < ActiveRecord::Base

  belongs_to :event
  has_many :events
  has_many :venues, :through => :event
  has_many :bookings, :through => :event
  has_many :genres, :through => :event

  def self.search(search)
    where("act_name LIKE ?", "%#{search}%")
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  require 'time'

  belongs_to :event
  belongs_to :user
  has_many :venues, :through => :event
  has_many :acts, :through => :event
  has_many :genres, :through => :event

  scope :unpaid, -> {where(:paid => nil)}
  scope :paid, -> {where(:paid => true)}

  def self.unpaid_grouped_events
    Booking.unpaid.group("event_id")
  end

  def expired?
    (Time.now - 100) > created_at
  end
  #7200 - 2 hours

  def self.two_hour_bookings
    checkout_bookings = Booking.unpaid
    counter = 0;
    checkout_bookings.each do |booking|
      if booking.expired?
        booking.destroy
        counter += 1
      end
    end
    return counter
  end

end

app/models/controller.rb
class Controller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :act
  belongs_to :venue
  belongs_to :feature
  has_many :bookings
  has_many :users, :through => :bookings
  has_many :event_genres
  has_many :genres, :through => :event_genres

  def self.search(search)
    where("event_details LIKE ?", "%#{search}%")
  end

  def double_booking?
    self.venue.events.each do |event|
      if event == self
        next
      end
      range = (event.event_start_time.to_i .. event.event_end_time.to_i)
      if (range) === self.event_start_time.to_i
        return "Event already Booked at this Time at this Venue"
      elsif (range) === self.event_end_time.to_i
        return "Event already Booked at this Time at this Venue"
      end
    end
    return nil
  end

  def tickets_left?
    event = Event.find(self.id)
    booking_count = event.bookings.count
    tickets_left = event.venue.venue_capacity - booking_count
  end

  def sold_out?
    event = Event.find(self.id)
    booking_count = event.bookings.count
    tickets_left = event.venue.venue_capacity - booking_count
    if tickets_left > event.venue.venue_capacity
      return true
    else
      return false
    end
  end

end

app/models/event_genre.rb
class EventGenre < ActiveRecord::Base

  belongs_to :event
  belongs_to :genre

end

app/models/feature.rb
class Feature < ActiveRecord::Base

  belongs_to :event

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :event_genres
  has_many :events, :through => :event_genres

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
  has_many :events, :through => :bookings

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base

  belongs_to :event
  has_many :events
  has_many :acts, :through => :event
  has_many :bookings, :through => :event

  def self.search(search)
    by_location = where("venue_location LIKE ?", "%#{search}%")
    by_name = where("venue_name LIKE ?", "%#{search}%")
    (by_location + by_name).uniq
  end

end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  def index
  end

  def show
    @act = Act.find(params[:id])    
  end

  def all_events
    @act = Act.find(params[:id])
  end

  def edit
    @act = Act.find(params[:id])
  end

  def update
    act = Act.find(params[:id])
    act.update(act_params)
    redirect_to admin_index_path
  end

  def new
    @act = Act.new
  end

  def create
    act = Act.new(act_params)
    act.save
    redirect_to admin_index_path
  end

  private

    def act_params
      params.require(:act).permit(:act_name, :act_details, :act_image)
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def index
    @events = Event.all
    @venues = Venue.all
    @bookings = Booking.all
    @users = User.all
    @acts = Act.all
    @featured = Feature.all
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    
    @genres = Genre.all
    @events = Event.all
    @bookings = Booking.all
    @featured = Feature.all

  end

  def show
    
    @event = Event.find(params[:id])
    
  end

  def edit
    @event = Event.find(params[:id])
    @acts = Act.all
    @venues = Venue.all
  end

  def update
    event = Event.find(params[:id])
    double_booking = event.double_booking?
    if double_booking
      redirect_to edit_event_path(event.id), alert: ("Fail: #{double_booking}")
      return
    end
    event.update(event_params)
    redirect_to admin_index_path
  end

  def new
    @event = Event.new
    @acts = Act.all
    @venues = Venue.all
  end

  def create
    event_new = Event.new(event_params)
    double_booking = event_new.double_booking?
    if double_booking
      redirect_to new_event_path, alert: ("Fail: #{double_booking}")
      return
    end
    event_new.save
    redirect_to admin_index_path
  end

  def search
    
      if params[:search]
        @events = Event.search(params[:search])
        @acts = Act.search(params[:search])#.order("ingredient_name DESC")
        @venues = Venue.search(params[:search])
        @genres = Genre.search(params[:search])
      else
        @event = Event.all.order("event_details DESC")
      end
  end

  private

    def event_params
      params.require(:event).permit(:event_details, :event_price, :act_id, :venue_id, :event_start_time, :event_end_time)
    end

end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/admin_helper.rb
module AdminHelper

end

app/helpers/application_helper.rb
module ApplicationHelper

  def admin?
    current_user.role == "admin"
  end
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/acts/all_events.html.erb
<section class="row">
  <div class="grid grid-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <%= @act.act_name %>
      </div>
      <% @act.events.each do |event| %>
        <%= link_to "#{event.event_details}", event_path(event.id) %>
        <br>
        <%= event.event_start_time.strftime('%H:%M on %d %^b %Y') %>
        <br>
        <br>
      <% end %>
    </div>
  </div>
</section>

app/views/acts/edit.html.erb
<section class="row">
  <div class="grid grid-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
      <%= "#{@act.act_name}" %>
      </div>
        <%= form_for @act do |f| %>
          <%= f.label :act_name %>
          <%= f.text_field :act_name %>
          <br>
          <%= f.label :act_details %>
          <%= f.text_field :act_details, :rows => 20, :cols => 20 %>
          <br>
          <%= f.label :act_image %>
          <%= f.text_field :act_image %>
          <%= f.submit 'Edit Act!' %>
          <br>
          <br>
        <% end %>
    </div>
  </div>
</section>

app/views/acts/index.html.erb
<h1>Acts#index</h1>
<p>Find me in app/views/acts/index.html.erb</p>

app/views/acts/new.html.erb
<section class="row">
  <div class="grid grid-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
      <p>Add New Act</p>
      </div>
        <%= form_for @act do |f| %>
          <%= f.label :act_name %>
          <%= f.text_field :act_name %>
          <br>
          <%= f.label :act_details %>
          <%= f.text_field :act_details, :rows => 20, :cols => 20 %>
          <br>
          <%= f.label :act_image %>
          <%= f.text_field :act_image %>
          <br>
          <br>
          <%= f.submit 'Add Act!' %>
        <% end %>
    </div>
  </div>
</section>

app/views/acts/show.html.erb
<h1><%= @act.act_name %></h1>

<section class="row">
  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="individual-image">
        <%= image_tag @act.act_image %>
      </div>
      <%= link_to "See all #{@act.act_name}'s Events", {:controller => "acts", :action => "all_events", :id => @act.id} %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <%= @act.act_name %>
      <br>
      <br>
      <%= @act.act_details %>
    </div>
  </div>
</section>

app/views/events/edit.html.erb
<section class="row">
  <div class="grid grid-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
      <%= "#{@event.event_details}" %>
      </div>
        <%= form_for @event do |f| %>
          <%= f.label :event_details %>
          <%= f.text_field :event_details %>
          <br>
          <%= f.label :event_price %>
          <%= f.text_field :event_price %>
          <br>
          <%= f.label :act_id, "Act" %>
          <%= f.collection_select(:act_id, @acts, :id, :act_name, prompt: "Select Act") %>
          <br>
          <%= f.label :venue_id, "Act" %>
          <%= f.collection_select(:venue_id, @venues, :id, :venue_name, prompt: "Select Venue") %>
          <br>
          <%= f.label :event_start_time, "Start Time" %>
          <%= f.datetime_field :event_start_time%>
          <br>
          <%= f.label :event_end_time, "End Time" %>
          <%= f.datetime_field :event_end_time%>
          <br>
          <br>
          <%= f.submit 'Edit Event!' %>
        <% end %>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<section class="row">
  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading"><%= link_to "View All Categories", genres_path %></div>
        <h3><%= link_to "#{@genres.first.title}", genre_path(@genres.first.id) %></h3>
        <% @genres.first.events.first(4).each do |event| %>
          <%= link_to "#{event.event_details}", event_path(event.id) %>
          <br>
        <% end %>
        <br>
        <h3><%= link_to "#{@genres.second.title}", genre_path(@genres.second.id) %></h3>
        <% @genres.second.events.first(4).each do |event| %>
          <%= link_to "#{event.event_details}", event_path(event.id) %>
          <br>
        <% end %>
        <h3><%= link_to "#{@genres.third.title}", genre_path(@genres.third.id) %></h3>
        <% @genres.third.events.first(4).each do |event| %>
          <%= link_to "#{event.event_details}", event_path(event.id) %>
          <br>
        <% end %>
        <h3><%= link_to "#{@genres[3].title}", genre_path(@genres[3].id) %></h3>
        <% @genres[3].events.first(4).each do |event| %>
          <%= link_to "#{event.event_details}", event_path(event.id) %>
          <br>
        <% end %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Featured Events</div>
        <% @featured.each do |feature| %>
          <div class="feature-box">
            <h3><%= link_to "#{feature.event.event_details}", event_path(feature.event.id) %></h3>
            <div class="feature-image">
              <%= image_tag feature.event.act.act_image %>
            </div>
          </div>
          <br>
          <br>
        <% end %>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<section class="row">
  <div class="grid grid-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
      <p>Add New Event</p>
      </div>
        <%= form_for @event do |f| %>
          <%= f.label :event_details %>
          <%= f.text_field :event_details %>
          <br>
          <%= f.label :event_price %>
          <%= f.text_field :event_price %>
          <br>
          <%= f.label :act_id, "Act" %>
          <%= f.collection_select(:act_id, @acts, :id, :act_name, prompt: "Select Act") %>
          <br>
          <%= f.label :venue_id, "Act" %>
          <%= f.collection_select(:venue_id, @venues, :id, :venue_name, prompt: "Select Venue") %>
          <br>
          <%= f.label :event_start_time, "Start Time" %>
          <%= f.datetime_field :event_start_time%>
          <br>
          <%= f.label :event_end_time, "End Time" %>
          <%= f.datetime_field :event_end_time%>
          <br>
          <br>
          <%= f.submit 'Add Event!' %>
        <% end %>
    </div>
  </div>
</section>

app/views/events/search.html.erb
<% if @events.present? || @acts.present? || @venues.present? || @genres.present? %>

    <% if @events.present? %>
      <% @events.each do |event| %>
        <h3><%= link_to "#{event.event_details}", event_path(event.id) %></h3>
      <% end %>
    <% end %>

    <% if @acts.present? %>
      <% @acts.each do |act| %>
        <h3> <%= link_to "#{act.act_name}", act_path(act.id) %> </h3>
      <% end %>
    <% end %>

    <% if @venues.present? %>
      <% @venues.each do |venue| %>
        <h3> <%= link_to "#{venue.venue_name}", venue_path(venue.id) %> </h3>
      <% end %>
    <% end %>

    <% if @genres.present? %>
      <% @genres.each do |genre| %>
        <h3> <%= link_to "#{genre.title}", genre_path(genre.id) %> </h3>
      <% end %>
    <% end %>

  <% else %>
    <h3>There are no SEARCH RESULT containing: <%= params[:search] %></h3>
  <% end %>

app/views/events/show.html.erb
<h1><%= @event.event_details %></h1>

<section class="row">
  <div class="grid grid-6">
    <div class="panel panel-primary">
      <div class="individual-image">
        <%= image_tag @event.act.act_image %>  
      </div>
      <% if @event.sold_out? %>
        <h1><%= "SOLD OUT" %><h1>
      <% else %>
        <%= "#{@event.tickets_left?} Tickets Left" %>
        <h3><%= link_to "Book This Event Now!", current_user ? new_event_booking_path(@event) : new_user_session_path %></h3>
      <% end %>
    </div>
  </div>

  <div class="grid grid-6">
    <div class="panel panel-primary">
      <%= @event.act.act_name %>
      <br>
      <br>
      <%= link_to "#{@event.venue.venue_name}", venue_path(params[:id]) %>
      <br>
      <br>
      <%= @event.event_start_time.strftime('%H:%M on %d %^b %Y') %>
      <br>
      <br>
      £<%= @event.event_price %>
      <br>
      <br>
      <%= @event.act.act_details %>
    </div>
  </div>
</section>